
export default {
  application: {
    applicant_other_idea: '如果你还有其他的创业想法，也请一并告诉我们。这也许会成为我们录取的重要原因',
    applicant_surprising_thing: '请告诉我们一件你们发现的奇妙或有趣的事情',
    application_awareness_channel: '你是从什么渠道了解到我们的创业营申请呢？',
    application_introducer: '如果有，请填写推荐人姓名，推荐人可以包括奇绩团队成员，奇绩校友，投资人等。',
    application_reason: '是什么原因促使你决定申请奇绩创坛的项目呢？',
    company_cap_table: '请描述创始人、员工和其他股东的持股比例，包括期权池比例。如果有多个创始人，请列举每个人计划中的股份分配（如果公司还未成立，请叙述计划中的股权分配）',
    company_category: '公司的业务属于哪个类别？',
    company_debt: '公司是否存在（或创始人是否存在为公司而产生的）任何借款、负债？如果存在，请予以说明。',
    company_difference: '与上次申请相比，主要的进展和变化有哪些（若有）',
    company_has_investment: '公司是否收到过投资？',
    company_investment: '请罗列公司已经收到的所有投资，包括投资方、投资额度、投资前估值',
    company_lawsuit: '有没有任何法律或债务上的纠纷？',
    company_legal_entity: '你的公司是否已经注册，或者有了法律主体？',
    company_name: '公司名称 （如果公司还未注册，可填写预想名称）',
    company_progress: '你们公司近六个月的进展如何？（技术开发、用户获取、营收和融资等）',
    company_registration: '如果已经注册，该公司注册地点在哪里？如果还没有注册公司，你们的公司计划注册在哪？',
    company_revenue_growth: '关于公司营收或业务增长，还有什么是你想和我们分享的信息呢？',
    company_runway: '现有资金还能支撑公司运营多久？',
    company_url: '如有公司官网，请提供链接',
    customer_problem: '你的用户是谁？你为他们解决什么问题？',
    demo_url: '如果已经有了产品demo，请提供链接。非软件类的产品，可以提供视频',
    first_time_hear_about: '你第一次是通过什么方式听说奇绩创坛的？',
    founder_commitment: '创始团队每个人累计为现有产品付出了多长时间？是全职创业还是兼职？请说明原因',
    founder_noncompete: '有没有任何创始人受到与你们的产品相关的竞业禁止或知识产权合同的约束？如果存在，请予以解释',
    founder_number: '有几位创始人拥有超过2%的股权？（回答的数字要和“创始团队”部分填写的创始人数量一致，最多填写5位）',
    founder_number_html: '有几位创始人拥有超过2%的股权？<b>（回答的数字要和“创始团队”部分填写的创始人数量一致，最多填写5位）',
    founder_relation: '核心团队如何认识的？',
    founder_residence: '请问你目前居住和办公在哪个城市？',
    genius_friend: '请你列举出一位你身边的人才 （创业者，行业专家，有潜力的年轻人等），简述理由，并附联系方式',
    main_founder_career_stage: '核心创始人目前所处的职业阶段是？',
    product_business_model: '你的商业模式是什么？你预测你做的这个市场有多大？',
    product_competitor: '现有竞争对手和潜在竞争对手是谁？你最害怕谁？请具体提供与现在市场上竞品的比较分析',
    product_description: '请简单描述一下公司的产品',
    product_differentiator: '你的产品有什么特别的地方？现在用户在使用什么替代品？',
    product_former_employer: '是否有任何核心产品是在前雇主工作期间开发的？',
    product_inspiration: '你为什么会选这个想法来创业？你在这个行业有什么专业知识？',
    product_introduction: '请对产品进行一句话概括（15字以内，如“极其方便的云端协作文档”、“开源自动驾驶技术”）',
    product_metric: '在你这个赛道，取得成功的要素有哪几个？',
    product_name: '产品名称',
    product_owner: '产品IP所有权人是谁？公司使用该IP是否受到任何限制？',
    product_plan: '产品原型或者测试版计划何时进入市场呢？如果已经上线，是什么时候上线的？',
    product_plan_biotech: '计划开发的产品（服务、诊断、药物等）和开发时间表及预算',
    product_plan_hardware: '当前你的产品研发进展是什么阶段了？是否已经完成样机和测试？是否已经开始销售？预计什么时间可以正式开始销售？',
    product_status: '公司的产品或者服务已经开始进入市场了吗？',
    product_timing: '为什么现在是最好时机做这个事？有什么市场驱动因素产生？',
    product_understanding: '在你的行业里，有什么大多数人都不同意的但你认为是对的观点？',
    revenue_number: '如果有收入，请填写过去六个月里每个月的实际收入',
    revenue_status: '项目是否已经有营收？',
    user_acquisition: '你怎样获得早期用户？',
    user_number: '如果已经进入市场，你们的产品有多少活跃用户了？每月增长如何？',
    user_number_biotech: '请描述技术平台的原理（如有相关文章发表，请列出）。该技术平台上公司内部是否有进行过验证？如有，请展示相关项目的验证性数据总结',
    user_number_hardware: '如果已经开始销售，已经有多少客户了？增长如何？',
  },
  founder: {
    applicant_share: '在你所代表的申请公司中，你占股至少2%吗？',
    founder_date_of_birth: '出生日期',
    founder_education: '教育经历 - 学校、专业、学位和毕业年份',
    founder_email: '电子邮箱',
    founder_form_title: '请添加每个拥有至少5%股权的创始人，包括你自己',
    founder_future_commitment: '未来3年里，这份创业之外，你还有其他安排或承诺过要完成的事吗？如果有，是什么？',
    founder_hack_experience: '请描述一次你打破常规并付诸实践的经历',
    founder_impressive_experience: '请用一两句话说说，除了创建这家公司之外，你做过最了不起的事是什么？',
    founder_name: '全名',
    founder_phone: '电话号码',
    founder_technical_background: '你是个技术型创始人吗？',
    founder_wechat_id: '微信ID',
    founder_work_experience: '工作经历 - 工作过的公司，职位/头衔和日期',
  },
};
